services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Infrastructure\Controller\CreateBikeController:
    class: App\Infrastructure\Controller\CreateBikeController
    tags: ['controller.service_arguments']

  App\Infrastructure\Controller\GetBikeByIdController:
    class: App\Infrastructure\Controller\GetBikeByIdController
    tags: ['controller.service_arguments']

  App\Infrastructure\Controller\GetBikesController:
    class: App\Infrastructure\Controller\GetBikesController
    tags: ['controller.service_arguments'] 

  App\Infrastructure\Controller\UpdateBikeController:
    class: App\Infrastructure\Controller\UpdateBikeController
    tags: ['controller.service_arguments']   

  App\Infrastructure\Persistence\Doctrine\Repository\DoctrineBikeRepository:
    class: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineBikeRepository
    factory: ["@doctrine", getRepository]
    arguments: ["App\\Domain\\Entity\\Bike"]

  App\Infrastructure\Persistence\Doctrine\DataFixtures\:
    resource: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/DataFixtures'
    tags:
      - 'doctrine.fixture.orm'
  

      