services:
    php:
        build:
            context: ./docker/php
            args: ["HOST_IP=${DOCKER_HOST_IP}"]
        container_name: php
        restart: unless-stopped
        env_file: .env
        ports: ["8888:80"]
        volumes:
            - "./:/app"
        tty: true

    mysql:
        build:
            context: ./docker/mysql
        container_name: mysql
        restart: unless-stopped
        env_file: .env
        ports: ["3300:3306"]
        tty: true

networks:
    default:
        name: apinet
        external: true

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
